services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    command: "php public/server.php"
    networks:
      - swoole

networks:
  swoole:
    driver: bridge
